### ISSUE TITLE
Issue with targeted nameplate

### ISSUE THREAD

**Issue by Flecked42** [MarcelineVQ/TankPlates#4]
Targeted nameplate doesn't have the + symbol for elites with pfUI.

![WoWScrnShot_052024_203151](https://github.com/MarcelineVQ/TankPlates/assets/90434262/89b6ed43-86e5-4a21-98ab-f7d6c45c6e72)

**Comment by MarcelineVQ** [comment]
This is a byproduct of me changing the mob name, and pfui uses the name to look up if it's elite. A pfui that was using SuperWoW could just query the plate for elite status directly and be compatible.
Maybe I can make the current target obvious without the added `-`, though I quite like them

**Comment by Flecked42** [comment]
Ah i see. Thanks fixed.
