### ISSUE TITLE
Issue with text highlight on target

### ISSUE THREAD

**Issue by Flecked42** [MarcelineVQ/TankPlates#8]
The text highlight for the enemy you're targeting can be on multiple mobs.

![WoWScrnShot_060224_190501](https://github.com/MarcelineVQ/TankPlates/assets/90434262/9b05a971-93eb-4d25-b6ec-cbba74e3dfd0)

**Comment by MarcelineVQ** [comment]
Oopsie pretty sure I know exactly where that happened, will fixup and test later

**Comment by Flecked42** [comment]
Seems fixed, closing.
